[profile.dev]
strip = false
opt-level = 1

[profile.release]
strip = true
lto = true

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["client", "server"]
resolver = "2"
